### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by CoenWarmer** [MartijnDevNull/ticketnak#1]
Thanks 👍

**Comment by noisesfromspace** [comment]
No problem!

**Comment by noisesfromspace** [comment]
Btw I fixed some timezone issue so if you want to use this pull

**Comment by petersch87** [comment]
Hi Martijn,

You build an awesome service and I would love to get it working. But guess what; i have no clue what I am doing. I have no experience with github, python etc. 

I have tried my best, but can't get it up and running. This is how far I got: I grabbed your files, got the event id, made a facebookapp and added the info in the facebookfile. I downloaded and installed python 3.6 but thats as far as I get. 

I don't know what you mean with the next steps in your Installation guide - from cd ticketnak and forward. Are these all commands in python?

**Comment by noisesfromspace** [comment]
Hey Peter,

The project needs a few dependencies. It's common practice to do this in a virtual environment when you run multiple projects but I'm guessing this is the only python project you're going to be running haha.

You can skip the virtualenv and source commands but you do have to install the dependencies. I'm assuming you run Windows? In that case pip is installed with Python so you can just follow these instructions: https://stackoverflow.com/a/14407505/1572635 and then install the dependencies with the other commands listed in the README

Let me know how it goes

**Comment by GideonMooijen** [comment]
Hi Martijn,

Thanks for the code. One question: in the facebook.ini-default file there are 5 blanks. All the FB ones  are selfexplanatory, but what do I fill in for TICKETSWAP_SESSION? In my case: is it 2153094?
https://www.ticketswap.nl/wanted/2153094

Thanks!

**Comment by noisesfromspace** [comment]
The Ticketswap session is your user session which is used to reserve the ticket. You can find it by CTRL+SHIFT+j and going to the Application > Cookies page. See link http://imgur.com/a/blast

**Comment by noisesfromspace** [comment]
Closing this, please make separate issues for help

**Comment by petersch87** [comment]
Hi Martijn,

Uiteindelijk is het gelukt, onwijs bedankt voor je hulp en de code. Wat een
festivalsaver!!

Groeten Peter

Op 31 jul. 2017 16:04 schreef "Martijn Boers" <notifications@github.com>:
