### ISSUE TITLE
Super nice! Maar werkt het echt

### ISSUE THREAD

**Issue by jasperrooduijn** [MartijnDevNull/ticketnak#2]
Super nice!! Ik had de boel zo draaien en heb de 'bot' vol verwachting aangezwengeld. Maar ik heb het idee dat het niet werkt. Ik heb jouw script gekoppeld aan een event. Ik krijg wel steeds push notificaties via de app maar het script doet verder niets.

Kan dit kloppen? Is het zo dat niet alle aangeboden kaarten op de event page van Facebook komen. En daarom niet door het script worden opgepakt?

**Comment by noisesfromspace** [comment]
Ik ga er even naar kijken, volgens mij zijn er een aantal dingen veranderd waardoor deze nu niet meer werkt. Helaas is mijn Ticketswap account geblokkeerd (hoe zou dat komen haha) dus moet dat eerst even oplossen

Edit: De /reserve API endpoint geeft voor mij een 403 op verschillende Facebook accounts en IP adressen. Ben heel erg benieuwd hoe ze mij zo buiten hebben kunnen sluiten haha

**Comment by jasperrooduijn** [comment]
Wellicht op basis van IP? Misschien kun je is proberen met een VPN ofz...

Edit: sorry had je bericht (verschillende IP adressen) niet goed gelezen.

**Comment by jasperrooduijn** [comment]
Dus we moeten concluderen dat dit script niet meer gaat werken dan denk ik?

**Comment by noisesfromspace** [comment]
Voor nu in ieder geval niet, andere scripts hebben hier ook last van (https://github.com/matthisk/TicketScoop/issues/14). Ik ga proberen nog om de blokkade heen te komen, maar weet niet of dit gaat lukken. Het script kan nog steeds detecteren als er een nieuwe ticket wordt aangeboden op Facebook en deze in een browser openen maar het reserveren van dit ticket blijft even niet mogelijk.
