### ISSUE TITLE
is this repository works on ubuntu

### ISSUE THREAD

**Issue by itbidhan** [MartijnDevNull/ticketnak#4]
hello i wants to use this into my ubuntu, is this will work on my ubuntu @MartijnDevNull

**Comment by noisesfromspace** [comment]
This will work on Ubuntu, working on Arch Linux myself but will have to wait for Facebook to lift it's restrictions on the Graph API for it to work: https://newsroom.fb.com/news/2018/03/cracking-down-on-platform-abuse/
